### ISSUE TITLE
请问在ux文件中导出custome——page有举例吗

### ISSUE THREAD

**Issue by chinahuwenjia** [MysticalFE/quickapp-log#3]
在.ux文件script标签中导出Custom_page,export default Custom_page({....})

这个不是很明白什么意思。。麻烦你了

**Comment by MysticalFE** [comment]
> 在.ux文件script标签中导出Custom_page,export default Custom_page({....})
> 
> 这个不是很明白什么意思。。麻烦你了

假设你项目是vue工程项目，你的页面应该是这样写

```
<template>
...
</template>
<script>
 export default Custom_page({
    data() {
       return {}
   },
   ......
})
</script>

```

在日志统一处理的逻辑中就可以拿到当前的实例vm, 对当前实例中定义的方法进行拦截处理
 

以上在快应用中逻辑上是一致的
